/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online;

import javax.swing.JScrollBar;
import javax.swing.JScrollPane;


public class Dashboard extends javax.swing.JFrame {

   String pItem;
    public String amt;
   public String amt2;
   public String amt3;
   public String amt4;
   public String amt5;
   public String amt6;
   public double firstamount;
   public double secondamount;
   public double thirdamount;
   public double fourthamount;
   public double fifthamount;
   public double sixthamount;
   public double amtCollected;
   public double grandTotal;
   public double perunit;
   public double qtypurchased;
   public double totalAmount;
   public double transactionNo;
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opnChange = new javax.swing.JOptionPane();
        btngroupPaymentMode = new javax.swing.ButtonGroup();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainPanel = new javax.swing.JPanel();
        CustomerPurchase = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboProductCategory = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtPricePerUnit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQtypurchased = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        firstItemtxt = new javax.swing.JTextField();
        secondItemtxt = new javax.swing.JTextField();
        thirdItemtxt = new javax.swing.JTextField();
        fourthItemtxt = new javax.swing.JTextField();
        fifthItemtxt = new javax.swing.JTextField();
        sixthItemtxt = new javax.swing.JTextField();
        txtGrandTotal = new javax.swing.JTextField();
        chkboxFirstItem = new javax.swing.JCheckBox();
        chkboxSecondItem = new javax.swing.JCheckBox();
        chkboxThirdItem = new javax.swing.JCheckBox();
        chkboxFourthItem = new javax.swing.JCheckBox();
        chkboxFifthItem = new javax.swing.JCheckBox();
        chkboxSixthItem = new javax.swing.JCheckBox();
        chkboxGrandTotal = new javax.swing.JCheckBox();
        comboBoxProductName = new javax.swing.JComboBox<>();
        panelChangeCalculator = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtAmtCollected = new javax.swing.JTextField();
        txtamtPurchased = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        btnGetBalance = new javax.swing.JButton();
        multiPanel = new javax.swing.JPanel();
        tbPaneReceipt = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReceipt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        PaymentModePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stef-Nita Customer Purchase Entry");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1800, 1100));
        setPreferredSize(new java.awt.Dimension(1700, 1000));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 40)); // NOI18N
        jLabel14.setText("Stef- Nita's Customer Sales Entry Manager");

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1500, 1000));

        MainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 10));
        MainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainPanelMouseEntered(evt);
            }
        });

        CustomerPurchase.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        CustomerPurchase.setMaximumSize(new java.awt.Dimension(400, 200));

        jLabel1.setText("Product Name");

        jLabel2.setText("Product Category");

        comboProductCategory.setEditable(true);
        comboProductCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alcoholic Drink", "Soft Drink/Beverages", "Provisions and Packed Foods", "Furniture", "Home Appliances", "Kitchen Utensils", "Perfumes", "Soap and Creams", "Toys", " ", " " }));

        jLabel3.setText(" Price per unit");

        txtPricePerUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPricePerUnitActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantity Purchased");

        txtQtypurchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtypurchasedActionPerformed(evt);
            }
        });

        lblTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalAmount.setText("Total Amount");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 0, 0));
        btnEnter.setText("Calculate and Register");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        thirdItemtxt.setMaximumSize(new java.awt.Dimension(6, 20));
        thirdItemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdItemtxtActionPerformed(evt);
            }
        });

        fourthItemtxt.setMaximumSize(new java.awt.Dimension(6, 20));

        txtGrandTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        chkboxFirstItem.setText("First Item");
        chkboxFirstItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxFirstItemActionPerformed(evt);
            }
        });

        chkboxSecondItem.setText("Second Item");

        chkboxThirdItem.setText("Third Item");

        chkboxFourthItem.setText("Fourth Item");

        chkboxFifthItem.setText("Fifth Item");

        chkboxSixthItem.setText("Sixth Item");

        chkboxGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chkboxGrandTotal.setText("GrandTotal");
        chkboxGrandTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxGrandTotalActionPerformed(evt);
            }
        });

        comboBoxProductName.setEditable(true);
        comboBoxProductName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Product", "Fanta", "Coke", "Sprite", "Pepsi", "seven-Up", "La Casera", "ChapMan", "Schweppes", "H2O", "Soda Water", "Soda Cream", "Body White ", "Miss Caroline ", "Fair & White", "Caro Fair ", "Refridgerator", "Deep Freezers", "Pressing Iron", "Washing Machi", " ", " " }));
        comboBoxProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProductNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerPurchaseLayout = new javax.swing.GroupLayout(CustomerPurchase);
        CustomerPurchase.setLayout(CustomerPurchaseLayout);
        CustomerPurchaseLayout.setHorizontalGroup(
            CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPurchaseLayout.createSequentialGroup()
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPricePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5)
                                    .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtQtypurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                            .addComponent(lblTotalAmount)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxSixthItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sixthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxFifthItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fifthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxFourthItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fourthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxThirdItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(thirdItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxSecondItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(secondItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addComponent(chkboxFirstItem)
                                .addGap(49, 49, 49)
                                .addComponent(firstItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkboxGrandTotal)
                        .addGap(18, 18, 18)
                        .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        CustomerPurchaseLayout.setVerticalGroup(
            CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkboxFirstItem)
                    .addComponent(firstItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(secondItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkboxSecondItem))
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPricePerUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxThirdItem)
                            .addComponent(thirdItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkboxFifthItem)
                            .addComponent(fifthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkboxSixthItem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtQtypurchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CustomerPurchaseLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chkboxFourthItem)
                                    .addComponent(fourthItemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalAmount)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)))
                .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerPurchaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkboxGrandTotal)
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(90, 90, 90))
        );

        panelChangeCalculator.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Change Calculator");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Amount Collected");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Amount Purchased");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("BALANCE");

        btnGetBalance.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGetBalance.setText("Get Balance");
        btnGetBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGetBalanceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelChangeCalculatorLayout = new javax.swing.GroupLayout(panelChangeCalculator);
        panelChangeCalculator.setLayout(panelChangeCalculatorLayout);
        panelChangeCalculatorLayout.setHorizontalGroup(
            panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeCalculatorLayout.createSequentialGroup()
                .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelChangeCalculatorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel18))
                        .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelChangeCalculatorLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtAmtCollected, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangeCalculatorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtamtPurchased, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelChangeCalculatorLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelChangeCalculatorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGetBalance)
                .addGap(67, 67, 67))
        );
        panelChangeCalculatorLayout.setVerticalGroup(
            panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelChangeCalculatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtAmtCollected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtamtPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelChangeCalculatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGetBalance)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        multiPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        txtAreaReceipt.setColumns(20);
        txtAreaReceipt.setRows(5);
        jScrollPane1.setViewportView(txtAreaReceipt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbPaneReceipt.addTab("Receipt", jPanel2);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Print");

        javax.swing.GroupLayout multiPanelLayout = new javax.swing.GroupLayout(multiPanel);
        multiPanel.setLayout(multiPanelLayout);
        multiPanelLayout.setHorizontalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiPanelLayout.createSequentialGroup()
                        .addComponent(tbPaneReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(20, 20, 20))))
        );
        multiPanelLayout.setVerticalGroup(
            multiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tbPaneReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PaymentModePanel.setBackground(new java.awt.Color(153, 0, 153));
        PaymentModePanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Payment Mode");

        btngroupPaymentMode.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setText("Cash");

        btngroupPaymentMode.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setText("POS");

        javax.swing.GroupLayout PaymentModePanelLayout = new javax.swing.GroupLayout(PaymentModePanel);
        PaymentModePanel.setLayout(PaymentModePanelLayout);
        PaymentModePanelLayout.setHorizontalGroup(
            PaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentModePanelLayout.createSequentialGroup()
                .addGroup(PaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaymentModePanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6))
                    .addGroup(PaymentModePanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(PaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        PaymentModePanelLayout.setVerticalGroup(
            PaymentModePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentModePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(20, 20, 20)
                .addComponent(jRadioButton1)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CustomerPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelChangeCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaymentModePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(multiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(panelChangeCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PaymentModePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CustomerPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(527, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(MainPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 1186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        try {
             perunit = Double.parseDouble(txtPricePerUnit.getText());
             qtypurchased = Double.parseDouble(txtQtypurchased.getText());
                totalAmount = perunit * qtypurchased;
        
                amt = String.format("%.0f", totalAmount);
            txtAmount.setText(amt);
                      
            firstamount = Double.parseDouble(txtAmount.getText());
        
            amt = String.format("%.0f", firstamount);
            if (chkboxFirstItem.isSelected() && !chkboxSecondItem.isSelected()){
            firstItemtxt.setText(amt);
             txtAreaReceipt.append("**************************************" +"\nStefNita SuperMarket and Stores" + "\n**************************************" + 
                "\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + firstItemtxt.getText());
            txtAmount.setText("");
           
            txtPricePerUnit.setText("");
             txtQtypurchased.setText("");
            }
            
            else if (chkboxFirstItem.isSelected() && chkboxSecondItem.isSelected() && !chkboxThirdItem.isSelected()) {
            secondamount = Double.parseDouble(txtAmount.getText());
        
            amt2 = String.format("%.0f", secondamount);
            secondItemtxt.setText(amt2);
            txtAmount.setText("");
            txtPricePerUnit.setText("");
            txtAreaReceipt.append("\n\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + secondItemtxt.getText());
            comboBoxProductName.setSelectedItem("Select Product"); 
            txtQtypurchased.setText("");
            }
            
            else if (chkboxFirstItem.isSelected() && chkboxSecondItem.isSelected() && chkboxThirdItem.isSelected() && !chkboxFourthItem.isSelected()) {
            thirdamount = Double.parseDouble(txtAmount.getText());
        
            amt3 = String.format("%.0f", thirdamount);
            thirdItemtxt.setText(amt3);
            txtAmount.setText("");
            txtAreaReceipt.append("\n\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + thirdItemtxt.getText());
           
            comboBoxProductName.setSelectedItem("Select Product");
            txtPricePerUnit.setText("");
            txtQtypurchased.setText("");
            }
            
            else if (chkboxFirstItem.isSelected() && chkboxSecondItem.isSelected() && chkboxThirdItem.isSelected() && chkboxFourthItem.isSelected() && !chkboxFifthItem.isSelected()) {
            fourthamount = Double.parseDouble(txtAmount.getText());
        
            amt4 = String.format("%.0f", fourthamount);
            fourthItemtxt.setText(amt4);
            txtAmount.setText("");
            txtAreaReceipt.append("\n\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + fourthItemtxt.getText());
            comboBoxProductName.setSelectedItem("Select Product");
            txtPricePerUnit.setText("");
            txtQtypurchased.setText("");
            }
            
            else if (chkboxFirstItem.isSelected() && chkboxSecondItem.isSelected() && chkboxThirdItem.isSelected() && chkboxFourthItem.isSelected() && chkboxFifthItem.isSelected() && !chkboxSixthItem.isSelected()) {
           fifthamount = Double.parseDouble(txtAmount.getText());
        
            amt5 = String.format("%.0f", fifthamount);
            fifthItemtxt.setText(amt5);
            txtAmount.setText("");
            txtAreaReceipt.append("\n\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + fifthItemtxt.getText());
            comboBoxProductName.setSelectedItem("Select Product");
            txtPricePerUnit.setText("");
            txtQtypurchased.setText("");
            }
            
            else if (chkboxFirstItem.isSelected() && chkboxSecondItem.isSelected() && chkboxThirdItem.isSelected() && chkboxFourthItem.isSelected() && chkboxFifthItem.isSelected() && chkboxSixthItem.isSelected()) {
            sixthamount = Double.parseDouble(txtAmount.getText());
        
            amt6 = String.format("%.0f", sixthamount);
            sixthItemtxt.setText(amt6);
            txtAmount.setText("");
            txtAreaReceipt.append("\n\n" + comboBoxProductName.getSelectedItem() + " " + "\t\tPrice per unit: N" + txtPricePerUnit.getText() + 
                     "\nQty Purchased" + " " + txtQtypurchased.getText() + "\tTotal" + " " + sixthItemtxt.getText());
            comboBoxProductName.setSelectedItem("Select Product");
            txtPricePerUnit.setText("");
            txtQtypurchased.setText("");
            }  
        }
        catch (NumberFormatException e)
        {
            System.out.println("Continue");
        }
        
    }//GEN-LAST:event_btnEnterActionPerformed

    private void txtPricePerUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPricePerUnitActionPerformed
        
    }//GEN-LAST:event_txtPricePerUnitActionPerformed

    private void txtQtypurchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtypurchasedActionPerformed
        
    }//GEN-LAST:event_txtQtypurchasedActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        
       
        
    }//GEN-LAST:event_txtAmountActionPerformed

    private void chkboxFirstItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxFirstItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkboxFirstItemActionPerformed

    private void thirdItemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdItemtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thirdItemtxtActionPerformed

    private void chkboxGrandTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxGrandTotalActionPerformed
            grandTotal = (firstamount+secondamount+thirdamount+fourthamount+fifthamount+sixthamount);
            String gTotal = String.format("%.0f", grandTotal);
            try {
                if (chkboxGrandTotal.isSelected()){
                txtGrandTotal.setText(gTotal); 
                txtamtPurchased.setText(gTotal);
        
                }
                else if (!chkboxGrandTotal.isSelected()){
                txtGrandTotal.setText("");
                }
            } catch (NumberFormatException exp) {
               System.out.println(exp);
            }
    }//GEN-LAST:event_chkboxGrandTotalActionPerformed

    private void comboBoxProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProductNameActionPerformed
             pItem = (String) comboBoxProductName.getSelectedItem();
             if (pItem.contains("Fanta") || pItem.contains("Coke") || pItem.contains("Sprite") ||pItem.contains("seven-Up") || pItem.contains("Pepsi") || pItem.contains("La Casera") || pItem.contains("ChapMan") || pItem.contains("ChapMan") || pItem.contains("Soda Cream") || pItem.contains("Soda Water"))
             {
                 comboProductCategory.setSelectedItem("Soft Drink/Beverages");
             }       
            
    }//GEN-LAST:event_comboBoxProductNameActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    private void MainPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainPanelMouseEntered
           
    }//GEN-LAST:event_MainPanelMouseEntered

    private void btnGetBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetBalanceMouseClicked
    try {                  
            if (!txtAmtCollected.equals("")) {
            amtCollected = Double.parseDouble(txtAmtCollected.getText());
            double balance = amtCollected - grandTotal;
            String bal = String.format("%.0f", balance);
            txtBalance.setText(bal);
            }
            
            else 
            {
                opnChange.showMessageDialog(null, "Enter the amount received from the customer", "Warning", opnChange.WARNING_MESSAGE);
            }
        }
        catch (NumberFormatException exp) {
            System.out.println(exp);
        }
    }//GEN-LAST:event_btnGetBalanceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerPurchase;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PaymentModePanel;
    public javax.swing.JButton btnEnter;
    private javax.swing.JButton btnGetBalance;
    private javax.swing.ButtonGroup btngroupPaymentMode;
    private javax.swing.JCheckBox chkboxFifthItem;
    private javax.swing.JCheckBox chkboxFirstItem;
    private javax.swing.JCheckBox chkboxFourthItem;
    private javax.swing.JCheckBox chkboxGrandTotal;
    private javax.swing.JCheckBox chkboxSecondItem;
    private javax.swing.JCheckBox chkboxSixthItem;
    private javax.swing.JCheckBox chkboxThirdItem;
    private javax.swing.JComboBox<String> comboBoxProductName;
    private javax.swing.JComboBox<String> comboProductCategory;
    private javax.swing.JTextField fifthItemtxt;
    private javax.swing.JTextField firstItemtxt;
    private javax.swing.JTextField fourthItemtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JPanel multiPanel;
    private javax.swing.JOptionPane opnChange;
    private javax.swing.JPanel panelChangeCalculator;
    private javax.swing.JTextField secondItemtxt;
    private javax.swing.JTextField sixthItemtxt;
    private javax.swing.JTabbedPane tbPaneReceipt;
    private javax.swing.JTextField thirdItemtxt;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtAmtCollected;
    private javax.swing.JTextArea txtAreaReceipt;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPricePerUnit;
    private javax.swing.JTextField txtQtypurchased;
    private javax.swing.JTextField txtamtPurchased;
    // End of variables declaration//GEN-END:variables
}
